# Generated by Django 3.1.2 on 2020-10-10 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodPayement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_payement', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CommandWait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_command', models.CharField(max_length=600)),
                ('first_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
                ('tva', models.CharField(blank=True, max_length=500)),
                ('price_command', models.FloatField()),
                ('date_command', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('method_payement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payements.methodpayement')),
                ('products_buy', models.ManyToManyField(to='products.Products')),
            ],
        ),
        migrations.CreateModel(
            name='CommandDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payements.commandwait')),
            ],
        ),
    ]
